# -*- coding: utf-8 -*-
"""8TH_SEPT_ASSIGNMENT(21BCB7022)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13XM9PuMBF4zOBN6YDzppD6klWDqFPast

# **8TH_SEPT_ASSIGNMENT**

NAME:- Thakur Akshath Singh


REG NO:- 21BCB7022
"""

Assignment 8 th september
1.Take car crashes dataset from seaborn library
2.load the dataset
3.data visualiation
4.Inference is must for each and every graph
5.Submit it by wednesday in html format

Feedback - https://forms.gle/7vFfvANDVfvDxxW28

"""# Steps:
1.import the necessary libraries
2.import the dataset
3.Handling null values
4.Seperate Dependent and independent variables
5.Encoding
6.splitting into training and testing set
7.Feature scaling

## 1.import the necessary libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""## 2.import the dataset"""

print(sns.get_dataset_names())

dataset=sns.load_dataset('car_crashes')

dataset

sns.__version__

df.info()

df.head(5)

sns.scatterplot(x="total",y="speeding",data=df)

sns.scatterplot(x="speeding",y="alcohol",data=df)

sns.scatterplot(x="alcohol",y="not_distracted",data=df)

sns.lineplot(x="total",y="speeding",data=df,ci=None)

sns.lineplot(x="alcohol",y="not_distracted",data=df,ci=None)

sns.lineplot(x="no_previous",y="ins_premium",data=df,ci=None)

sns.distplot(df["total"])

sns.distplot(df["alcohol"])

sns.distplot(df["no_previous"])

sns.relplot(x="total",y="speeding",data=df,hue="alcohol")

sns.relplot(x="not_distracted",y="no_previous",data=df,hue="ins_premium")

sns.relplot(x="total",y="speeding",data=df,hue="abbrev")

df["speeding"].value_counts()

df["not_distracted"].value_counts()

df["no_previous"].value_counts()

sns.barplot(data=df,x="total",y="speeding",ci=None)

sns.barplot(data=df,x="alcohol",y="not_distracted",ci=None)

sns.barplot(data=df,x="no_previous",y="ins_premium",ci=None)

sns.barplot(data=df,x="alcohol",y="not_distracted",hue="no_previous")

sns.barplot(data=df,x="alcohol",y="not_distracted",hue="ins_premium")

sns.countplot(x="total",data=df)

sns.countplot(x="alcohol",data=df)

sns.countplot(x="not_distracted",data=df)

sns.jointplot(x="total",y="speeding",data=df)

sns.jointplot(x="alcohol",y="no_previous",data=df)

sns.jointplot(x="not_distracted",y="no_previous",data=df)

sns.boxplot(x="total",y="speeding",data=df)

sns.boxplot(x="not_distracted",y="total",data=df)

sns.boxplot(x="not_distracted",y="ins_premium",data=df)

corr=df.corr()
corr

sns.heatmap(corr,annot=True,cmap="YlGnBu")